# Generated by Django 5.1 on 2024-08-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0011_remove_userproductreview_product_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProductReview",
            new_name="Review",
        ),
    ]
