# Generated by Django 5.1 on 2024-08-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_rename_userproductreview_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="object_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
