# Generated by Django 5.1 on 2024-08-28 05:32

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("users", "0013_review_object_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"get_latest_by": "modified"},
        ),
        migrations.RenameField(
            model_name="review",
            old_name="review",
            new_name="description",
        ),
        migrations.AlterUniqueTogether(
            name="userproductreaction",
            unique_together={("product", "user")},
        ),
        migrations.RemoveField(
            model_name="review",
            name="date_reviewed",
        ),
        migrations.AddField(
            model_name="review",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="userproductreaction",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="userproductreaction",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="userproductreaction",
            name="reaction",
            field=models.CharField(
                blank=True,
                choices=[("like", "Like"), ("dislike", "Dislike")],
                max_length=8,
                null=True,
            ),
        ),
    ]
