# Generated by Django 5.1 on 2024-08-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_review_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userproductreaction",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userproductreaction",
            name="product",
        ),
        migrations.RemoveField(
            model_name="userproductreaction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="reacted_products",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="UserProductReaction",
        ),
    ]
