# Generated by Django 5.0.6 on 2024-07-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("priceoye_clone_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(default="user", max_length=11),
        ),
    ]
