# Generated by Django 5.1 on 2024-08-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("in_cart", "In cart"),
                    ("order_placed", "Order_Placed"),
                    ("under_processing", "under_processing"),
                    ("dispatched", "Dispatched"),
                    ("delivered", "Delivered"),
                ],
                default="in_cart",
                max_length=20,
            ),
        ),
    ]
