# Generated by Django 5.0.6 on 2024-08-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_total_price_alter_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("order_received", "Order_received"),
                    ("under_processing", "under_processing"),
                    ("Dispatched", "Dispatched"),
                    ("Delivered", "Delivered"),
                ],
                max_length=20,
            ),
        ),
    ]
