# Generated by Django 5.1 on 2024-09-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specificationcategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
